### PR TITLE
Versioning and global tool deployment

### PR DESCRIPTION
**Pull request by michael-emmi**
This PR aims to automate the publishing of dotnet global tools for Corral.

### CODE REVIEW

**Comment by michael-emmi** [comment]
@bkragl @zvonimir @akashlal thoughts about this one?

(Basically this replicates the versioning and releasing we have built for Boogie.)

Question for @akashlal: since Corral is currently unversioned, what version should we start at?
* fresh at v1.0.0
* matching Boogie at v2.4.4
* something different altogether?

**Comment by zvonimir** [comment]
To me it makes sense that this should be done for all tools that depend on Boogie, and so it is awesome that you are doing this. I can't really comment on the details of the implementation.

About the version number, I guess I would start with v1.0.0. I don't see a good reason to start with the current version of Boogie.

**Comment by michael-emmi** [comment]
> About the version number, I guess I would start with v1.0.0. I don't see a good reason to start with the current version of Boogie.

Ok, then let’s make sure to include #major in the first line of the merge commit message — that should generate the tag `v1.0.0`.

**Comment by michael-emmi** [comment]
> Perhaps the new build instructions should be added to the readme file.

Good idea, I’ll do that.

**Comment by michael-emmi** [comment]
**NOTE**: be sure to include `#major` in the first line of the merge commit when merging this.

**Comment by michael-emmi** [comment]
@akashlal any objections to this PR?

**Comment by michael-emmi** [comment]
Oh crap I merged by accident…

**Comment by michael-emmi** [comment]
Confirming with @akashlal this is OK; otherwise we can always create a revert PR.

**Comment by akashlal** [comment]
Looks good, thanks!

**Pull request merged**
