### PR TITLE
trace inlining algo update

### PR DESCRIPTION
**Pull request by mayanksolanki393**
The implementation has been updated to match the algorithm. This is not a complete implementation and needs further work.

### CODE REVIEW

**Comment by shazqadeer** [comment]
> The implementation has been updated to match the algorithm. 

Which algorithm? :-)

**Comment by prantikchatterjee** [comment]
> > The implementation has been updated to match the algorithm.
> 
> Which algorithm? :-)

Hi Shaz, we were trying out some modifications to Stratified Inlining. I will review the changes and pull it to my branch if it is fine.

**Comment by shazqadeer** [comment]
Of course. Totally up to you. I was curious if some well-known new algorithm is being implemented in Corral.

**Review by prantikchatterjee — COMMENTED** [review]
Backtracking works incorrectly.

**Pull request closed without merging**
