### PR TITLE
Update boogie

### PR DESCRIPTION
**Pull request by zvonimir**
Updated Boogie to its latest release.

### CODE REVIEW

**Comment by zvonimir** [comment]
Let's wait to merge this until performance issues are discussed.

**Comment by zvonimir** [comment]
@akashlal and @shuvendu-lahiri : I would appreciate your help with merging this in. As you can see from my latest few commits, I've been playing with Z3 options to get this to work reasonably well. The current setup works best on SMACK regressions, and in particular on the ones that do not have (a lot) of quantifiers. Putting back all of the old legacy Z3 options did not work that well.

It would be great at this point if one or both of you could run this branch of Corral on some large-scale benchmarks that you have on your end, just to see if there are (many) performance regressions being introduced.

**Comment by akashlal** [comment]
@zvonimir Sorry for the delay. I tried this out. First of all, I am getting some compiler errors in the project ConcurrentHoudini. I am ignoring that for now because corral still builds fine. 

Then I noticed a big performance regression. In the folder, `test\regression\smack`, I ran the command: 

`corral a.bpl /flags:config /trackAllVars /doNotUseLabels`

The master branch version takes around 4 seconds, whereas this branch takes 33 seconds. I dumped the z3 query and the flags are different. The master branch has the following flags:

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
(set-option :model.compact false)
(set-option :smt.array.weak true)
(set-option :smt.array.extensional false)
```

whereas the current branch has:

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :smt.array.extensional false)
(set-option :smt.mbqi false)
(set-option :model.compact false)
(set-option :model.v2 true)
(set-option :pp.bv_literals false)
```

I would like the set of z3 flags to be the same as before. If Boogie is no longer adding them by default, then we can pass them programmatically via Corral.

**Comment by zvonimir** [comment]
Please try this commit, which sets the legacy options as you requested (two commits before last): https://github.com/boogie-org/corral/pull/111/commits/e718178279384fd15b76bfe9264f4dcde5901f39

On Linux there are no compiler errors, not sure where this discrepancy is coming from.

**Comment by akashlal** [comment]
With e718178 I am getting the same behavior as master branch. The performance regression on the one example that I mentioned above does not happen. This look good to me. I don't have other "big" benchmarks handy at the moment. But given that it is best to keep pace with latest version of Boogie, I would be OK moving ahead with these changes. Any regressions downstream will have to be dealt at that time itself. Can you please prepare the PR at the commit that you mentioned? I can then merge.

**Comment by zvonimir** [comment]
Good to know. SMACK's behavior with the default flags was much worse, and even a lot of our small regressions were not passing. We are running some large tests now.

So I suggest we go with Boogie strategy and go with a minimal set of flags that are hard-coded (so with the most recent commit in this branch), and then set others using command line options. That way we can set flags that work best for us, and you and other users can do the same on your end.

Would you be ok with that?

**Comment by akashlal** [comment]
That sounds fine. A few things:
- Can I request that you add a corral flag, say `/oldCorralFlags`, that will add these Z3 flags back?
- I am surprised now by the fact that you are still seeing regressions with smack. Why should that be? New corral with the flag `/oldCorralFlags` should behave the same as old corral with the flag `/doNotUseLabels`. Has something else also changed in Boogie? Can you perhaps document some benchmark (smaller the better). Even if we decide to take the hit for now, we might want to come back and debug this.

**Comment by zvonimir** [comment]
But `/doNotUseLabels` was not set by default, right? So in SMACK we were never setting this flag, which I think means that we used to generate SMT queries with labels. Actually, I just confirmed this - indeed, in SMACK we have been generating queries with labels until now.
One thing I will now try is to run all of our regressions with the current master corral branch and with `/doNotUseLabels` flag passed to Corral.

**Comment by zvonimir** [comment]
Here is an update. The old Corral (i.e., current master) with `/doNotUseLabels` does not generate the same SMT queries as the new Corral from this branch.
In particular, while the old Corral with `/doNotUseLabels` does remove label attributes from queries (which is what putting this flag in achieves), it still uses functions of the form `(declare-fun %lbl%+0 () Bool)`. So it seems that the flag `/doNotUseLabels` was some kind of a partial label removal. The new Corral completely removes these functions as well. So I do not expect for the two to behave the same.

**Comment by zvonimir** [comment]
Ok, I added the `/oldCorralFlags` option that you suggested. Maybe we should now merge this and continue experimenting with settings after it gets merged?

**Comment by akashlal** [comment]
Alright, we can go ahead. Should I merge this PR or do you want me to merge at e718178?

**Comment by zvonimir** [comment]
This PR since it implements the `/oldCorralFlags` option. Thanks!

**Comment by akashlal** [comment]
Thanks @zvonimir. Merged.

**Pull request merged**
